name:                streamly-cassava
version:             0.2.0.0
github:              "litxio/streamly-cassava"
license:             BSD3
author:              "Richard Warfield"
maintainer:          "richard@litx.io"
copyright:           "2025 Richard Warfield"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            CSV streaming support via cassava for the streamly ecosystem
category:            Streaming

description:         Please see the README on GitHub at <https://github.com/litxio/streamly-cassava#readme>

dependencies:
- base >= 4.7 && < 5
- streamly >= 0.9
- streamly-core
- cassava
- bytestring
- mtl
- exceptions
- vector

library:
  source-dirs: src


tests:
  streamly-cassava-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - streamly-cassava
    - hspec
    - QuickCheck
    - quickcheck-instances
    - text
    - vector


benchmarks:
  streamly-cassava-bench:
    main:                Bench.hs
    source-dirs:         bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - streamly-cassava
    - weigh
    - criterion
    - streaming
    - streaming-cassava
    - streaming-with
    - streaming-bytestring
    - vector
